export enum CardType {
    RUNNER_ID = 'RUNNER_ID',
    RUNNER_EVENT = 'EVENT',
    RUNNER_PROGRAM = 'PROGRAM',
    RUNNER_HARDWARE = 'HARDWARE',
    RUNNER_RESOURCE = 'RESOURCE',
    CORPORATION_ID = 'CORPORATION_ID',
    CORPORATION_OPERATION = 'OPERATION',
    CORPORATION_ASSET = 'ASSET',
    CORPORATION_UPGRADE = 'UPGRADE',
    CORPORATION_AGENDA = 'AGENDA',
    CORPORATION_ICE = 'ICE'
}

export enum CardSubType {
    SUBTYPE_AI = 'AI'
}

export enum IceType {
    ICE_BARRIER = 'BARRIER',
    ICE_CODEGATE = 'CODEGATE',
    ICE_SENTRY = 'SENTRY'
}